### ISSUE TITLE
lede x86_64编译失败

### ISSUE THREAD

**Issue by datout** [281677160/build-openwrt#1]
日志一些报错的地方，大佬能否看下。 
make[3] -C package/boot/grub2 compile
 make[3] -C package/lean/kcptun compile
 make[3] -C feeds/packages/devel/meson host-compile
 make[3] -C package/lean/v2ray compile
 make[3] -C package/lean/package/v2ray-plugin compile
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
/workdir/openwrt/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 1
。
。
。
Building targets
github.com/xtls/go
# github.com/xtls/go
pkg/mod/github.com/xtls/go@v0.0.0-20200921133830-416584838a0f/auth.go:29:7: undefined: ecdsa.VerifyASN1
pkg/mod/github.com/xtls/go@v0.0.0-20200921133830-416584838a0f/key_schedule.go:177:16: xShared.FillBytes undefined (type *big.Int has no field or method FillBytes)

Cleaning module download cache (golang/go#27455)

make[3]: *** [/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-1.5.0/.built] Error 2
Makefile:74: recipe for target '/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-1.5.0/.built' failed
make[3]: Leaving directory '/workdir/openwrt/package/lean/package/v2ray-plugin'
time: package/lean/package/v2ray-plugin/compile#2.10#0.72#7.94
package/Makefile:111: recipe for target 'package/lean/package/v2ray-plugin/compile' failed
make[2]: *** [package/lean/package/v2ray-plugin/compile] Error 2
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
package/Makefile:107: recipe for target '/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/workdir/openwrt'
make: *** [world] Error 2
/workdir/openwrt/include/toplevel.mk:222: recipe for target 'world' failed
Error: Process completed with exit code 2.

**Comment by 281677160** [comment]
这个好像是luci-app-ssr-plus其中的v2ray或者v2ray-plugin有问题，你别选择luci-app-ssr-plus的编译看看

**Comment by 281677160** [comment]
用Lienol或者Project编译吧，选择luci-app-ssr-plus也没问题，lede的源码选择luci-app-ssr-plus会下载不了v2ray-plugin出错

**Comment by datout** [comment]
已经修复了

**Comment by 281677160** [comment]
哦，谢谢，要上班，我也不可能天天测试这些





---原始邮件---
发件人: "datout"<notifications@github.com&gt;
发送时间: 2020年10月5日(周一) 下午2:21
收件人: "281677160/build-openwrt"<build-openwrt@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"281677160"<281677160@qq.com&gt;;
主题: Re: [281677160/build-openwrt] lede x86_64编译失败 (#1)




 
已经修复了
