### ISSUE TITLE
Lede_nanopi_r2s编译问题

### ISSUE THREAD

**Issue by datout** [281677160/build-openwrt#11]
![image](https://user-images.githubusercontent.com/70312079/100222709-749b6a00-2f55-11eb-8ddc-4f6b1109056a.png)
卡在这一步，时间读秒也停止

**Comment by 281677160** [comment]
你打开了SSH远程连接了吧？SSH远程连接卡了，如果相隔的时间不超2分钟可以尝试刷新下网页看看能继续弹出来，如果相隔时间旧了，就要关闭了这个工作，继续再来




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/build-openwrt"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 晚上7:37
收件人:&nbsp;"281677160/build-openwrt"<build-openwrt@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[281677160/build-openwrt] Lede_nanopi_r2s编译问题 (#11)





 

 卡在这一步，时间读秒也停止

**Comment by datout** [comment]
> 你打开了SSH远程连接了吧？SSH远程连接卡了，如果相隔的时间不超2分钟可以尝试刷新下网页看看能继续弹出来，如果相隔时间旧了，就要关闭了这个工作，继续再来
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/build-openwrt" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月25日(星期三) 晚上7:37 收件人:&nbsp;"281677160/build-openwrt"<build-openwrt@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[281677160/build-openwrt] Lede_nanopi_r2s编译问题 (#11) 卡在这一步，时间读秒也停止 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

![image](https://user-images.githubusercontent.com/70312079/100294660-6a638500-2fc2-11eb-9a07-f53d81a5aa5f.png)
大佬 能否看下 这个是什么问题

**Comment by 281677160** [comment]
不了解，看不懂，你先别一下子选择那里多插件试试呗，先用我默认的编译，能成功就表示源码没问题了，不能成功就表示源码有问题
