### ISSUE TITLE
斐讯N1的lean固件,/opt/docker挂载目录能否换成/mnt/mmcblk1p3

### ISSUE THREAD

**Issue by chibm** [281677160/build-openwrt#28]
你的编译脚本做得非常好,一次成功.
只是我编译出来的docker-man的/opt/docker目录是挂载到/mnt/mmcblk1p2,只有944.6M,很快就满了
不知是否可以挂载到/mnt/mmcblk1p3上,这个有5.3G

**Comment by 281677160** [comment]
没研究过这方面的，没从下手啊

**Comment by 281677160** [comment]
请问一下N1的CPU频率跟温度显示，还有机型显示正常显示不？

**Comment by chibm** [comment]
> 请问一下N1的CPU频率跟温度显示，还有机型显示正常显示不？

CPU频率跟温度正常,都可以随着使用增减变化.机型正常显示.

关于挂载目录问题已解决,ssh手动改/etc/config/dockerd和/etc/config/dockerman配置即可.此issues关闭
