### ISSUE TITLE
斐讯N1固件编译后,占用artifact存储空间过大,无法进行第二次编译

### ISSUE THREAD

**Issue by chibm** [281677160/build-openwrt#29]
第一次编译成功后 ,因为会生成vplus,,贝壳云,s905x3等固件包,所以生成的文件有1+G大小,下载下来后也可以用.
不过当再次重新进行云编译后,会失败.应该是云存储空间占满了,无法上传文件.已用过delete删除了也没用.

Run actions/upload-artifact@v2
  with:
    name: .config_Lede_phicomm_n1_2021-01-03 12.55
    path: ./config
    if-no-files-found: warn
  env:
    REPO_TOKEN: 
    SCKEY: ***
    TZ: Asia/Shanghai
    GITHUB_RELEASE: https://github.com/281677160/build-openwrt/releases
    REPO_URL: https://github.com/coolsnowwolf/lede
    REPO_BRANCH: master
    CONFIG_FILE: .config
    WXFB_MESSAGE: Lede_phicomm_n1
    DIY_P1_SH: diy-1.sh
    DIY_P2_SH: diy-2.sh
    SSH_ACTIONS: true
    UPLOAD_BIN_DIR: false
    UPLOAD_CONFIG: true
    UPLOAD_FIRMWARE: false
    UPLOAD_COWTRANSFER: true
    UPLOAD_RELEASE: false
    SERVERCHAN_SCKEY: true
    date: 2021-01-03 12.55
    date1: 2021年01月03号-12点55分
    date2: 20210103-1255
    firmware_phicomm-n1: 21.01.03-125630-phicomm-n1-5.4.83-aarch64-openwrt-firmware
    firmware_vplus: 21.01.03-125627-vplus-5.4.83-aarch64-openwrt-firmware
    firmware_beikeyun: 21.01.03-125619-beikeyun-5.4.83-aarch64-openwrt-firmware
    firmware_l1pro: 21.01.03-125628-l1pro-5.4.83-aarch64-openwrt-firmware
    firmware_s905x3: 21.01.03-125629-s905x3-5.4.83-aarch64-openwrt-firmware
    FIRMWARE: /home/runner/work/build-lean-op/build-lean-op/openwrt/bin/targets/armvirt/64
With the provided path, there will be 1 file(s) uploaded
Error: Artifact storage quota has been hit. Unable to upload any new artifacts

![image](https://user-images.githubusercontent.com/67989598/103472674-fdb28600-4dca-11eb-8f65-90b7668c960b.png)

**Comment by 281677160** [comment]
公开仓库没有存储空间不足的问题的，除非是私库，我做测试的时候一天编译几十次都不会这样

**Comment by chibm** [comment]
> 公开仓库没有存储空间不足的问题的，除非是私库，我做测试的时候一天编译几十次都不会这样

我是私库,,看来是这个问题,此issues关闭
