### ISSUE TITLE
Lienol_openwrt_x64的默认配置编译出来会没有/etc/config/network文件

### ISSUE THREAD

**Issue by WoChen5770** [281677160/build-openwrt#50]
![image](https://user-images.githubusercontent.com/26268544/111729237-95435300-88a9-11eb-84a1-9ea8c6a9424f.png)
不知道是不是这个的原因

**Comment by 281677160** [comment]
这个文件一直有的，不过看不见，你用WinSCP连接路由器，然后在ntc/config里面建立一个network的文件就立马跳出来了，我也不知道是啥原因，因为云编译都是直接修改好IP才编译的，所以不需要编译后再来改IP，所以这个问题一直没人问，不过这个文件是存在的，隐藏了而已，我是不知道原因了

**Comment by 281677160** [comment]
![Uploading QQ截图20210319120520.png…]()

**Comment by 281677160** [comment]
![QQ截图20210319120520](https://user-images.githubusercontent.com/66651997/111730050-8067bf00-88ab-11eb-9c04-d024652af92c.png)

**Comment by 281677160** [comment]
真不懂是和解

**Comment by WoChen5770** [comment]
我编译几次了，还是不行，那个ssh都连不上

**Comment by WoChen5770** [comment]
https://github.com/WoChen5770/build-openwrt

**Comment by 281677160** [comment]
什么叫连不上？什么原因？

**Comment by WoChen5770** [comment]
> 什么叫连不上？什么原因？

就是ssh连不上 ping也不通 。失联

**Comment by WoChen5770** [comment]
我用vnc进去看，是没有这个文件，新建也没出现你那种情况

**Comment by 281677160** [comment]
那我就不懂了，同样编译你的找不到，我的可以找到，隐藏而已，好像也不影响使用，你说SSH连接不上，我也没搞懂，就修改个插件而已，怎么ping那个链接呢？

**Comment by WoChen5770** [comment]
ping lan的ip啊

**Comment by WoChen5770** [comment]
你的包给我试试看

**Comment by 281677160** [comment]
SSH连不上提示什么

**Comment by WoChen5770** [comment]
网络不通的连不上啊，op连网卡都没有。我不知道是不是我关了ipv6的原因

**Comment by 281677160** [comment]
https://github.com/281677160/Actions-OpenWrt/releases/download/update_Firmware/openwrt-lienol-x86-64-202103190952-Legacy.img.gz

你去下载安装看看吧

**Comment by 281677160** [comment]
那你自己去源码作者那里问题吧，编译出来的固件没网卡，呵呵，你的电脑或者比较新，网卡驱动没支持吧

**Comment by 281677160** [comment]
你的固件编译好后经过转换再安装？或者你安装OP的空间太小？这些都有可能造成没network的问题

**Comment by WoChen5770** [comment]
> 你的固件编译好后经过转换再安装？或者你安装OP的空间太小？这些都有可能造成没network的问题

![image](https://user-images.githubusercontent.com/26268544/111738738-d7c25b00-88bc-11eb-9264-e419c225d2df.png)
你给的也是没有这个文件。
没有转换，我各种固件 自己编译或者别人编译的我都刷过，这是第一次碰到这情况。
我同时编的lean的没有问题，估计还是Lienol的源码或者哪里选项没选对的原因

**Comment by WoChen5770** [comment]
初步结论是Lienol的源码可能不支持爱快的虚拟化网卡。

**Comment by 281677160** [comment]
没有这个事情，我就是爱快虚拟机安装的，编译出来没有network也修复了，不过我想多测试一下而已，明天就可以修复了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月21日(周日) 晚上9:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [281677160/build-openwrt] Lienol_openwrt_x64的默认配置编译出来会没有/etc/config/network文件 (#50)




 
初步结论是Lienol的源码可能不支持爱快的虚拟化网卡。

**Comment by WoChen5770** [comment]
> 没有这个事情，我就是爱快虚拟机安装的，编译出来没有network也修复了，不过我想多测试一下而已，明天就可以修复了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月21日(周日) 晚上9:48 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [281677160/build-openwrt] Lienol_openwrt_x64的默认配置编译出来会没有/etc/config/network文件 (#50) 初步结论是Lienol的源码可能不支持爱快的虚拟化网卡。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我直接用他的源码 并且默认配置编译也不行。
想来想去还是用pve算了，爱快的虚拟机性能不行。我500m的网经过爱快虚拟机测得只有300m
